
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - sam build
    
  post_build:      
    commands:
      - echo Build completed on `date`   
artifacts:
    files:      
      - ./.aws-sam/build/template.yaml
